#version 460
#extension GL_EXT_ray_query : require

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform accelerationStructureEXT topLevelAS;

struct RayInput
{
    vec4 origin_tmin;
    vec4 dir_tmax;
};

layout(std430, set = 0, binding = 1) readonly buffer InRayBuffer
{
    RayInput rays[];
};

layout(std430, set = 0, binding = 2) writeonly buffer OutHitBuffer
{
    uint hits[];
};

layout(push_constant) uniform PushConstants
{
    uint numRays;
};

void main()
{
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= numRays)
    {
        return;
    }

    vec3 origin = rays[idx].origin_tmin.xyz;
    float tmin = rays[idx].origin_tmin.w;
    vec3 dir = rays[idx].dir_tmax.xyz;
    float tmax = rays[idx].dir_tmax.w;

    rayQueryEXT query;
    rayQueryInitializeEXT(query, topLevelAS, gl_RayFlagsTerminateOnFirstHitEXT | gl_RayFlagsOpaqueEXT, 0xFF, origin, tmin, dir, tmax);
    rayQueryProceedEXT(query);

    uint isHit = (rayQueryGetIntersectionTypeEXT(query, true) != gl_RayQueryCommittedIntersectionNoneEXT) ? 1u : 0u;
    hits[idx] = isHit;
}