cmake_minimum_required(VERSION 4.0)
cmake_policy(SET CMP0091 NEW)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
project(matrix-engine)

add_subdirectory(clientdll)
add_subdirectory(engine)
add_subdirectory(gamedll)
add_subdirectory(libs/freetype/builds/windows/vc2010)
add_subdirectory(libs/libogg/win32/VS2010)
add_subdirectory(libs/libvorbis/win32/VS2010/libvorbis)
add_subdirectory(libs/libvorbis/win32/VS2010/libvorbisfile)
add_subdirectory(utils/mdlimporter)
add_subdirectory(utils/vbmcompiler)
