cmake_minimum_required(VERSION 4.0)
cmake_policy(SET CMP0091 NEW)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
project(matrix-engine)

add_subdirectory(clientdll)
add_subdirectory(engine)
add_subdirectory(gamedll)
add_subdirectory(utils/mdlimporter)
add_subdirectory(utils/vbmcompiler)
